title = "GridPack"
gitSourceBranch = "main"

[[classOrder]]
section = "ItemManagers"
classes = ["ItemManager", "Grid", "SingleSlot"]

[home]
enabled = true
includeReadme = false

[docasaurus]
url = "https://grid-pack.ifrex.xyz"
baseUrl = "/"